### PR TITLE
add tracing docs, and fix actual event struct

### PR DESCRIPTION
**Pull request by benfleis**
a bit of doc, and s/local/id/ on the struct. also added 'address' to the struct, future facing.

@wolski @CorgiMan

### CODE REVIEW

**Comment by jwolski** [comment]
woot!

your tcat pull request has yet to be merged though. can you get that in so that the docs point to something available on mainline tcurl?

**Comment by benfleis** [comment]
If that was possible, I would. I wrote tcat because I couldn't find anything already in existence. The docs refer to the branch, and I'll keep my fingers crossed. Otherwise I'll make my own tcat repo and put it there :/

**Comment by jwolski** [comment]
:/ oh yes, you're right. I didnt originally see that you made mention of the `tcat` branch. That's fine until we have an alternate solution.

one last request, can you put the Event Tracing material under the How Ringpop Works section of "Architecture, Design, Implementation"? That's where I originally though that Feature descriptions would live. Eventually we might pull up a Features section to top-level, but right now, I don't think it makes sense to have Event Tracing be top-level by itself.

**Comment by benfleis** [comment]
@jwolski wasn't sure if woot ~== lgtm, so I await a final :thumbsup:

**Comment by jwolski** [comment]
LOL

**Pull request merged**
