### PR TITLE
Permit alternate ring implementation

### PR DESCRIPTION
**Pull request by kriskowal**
e.g., jump consistent hash ring, Hilbert ring…

https://en.wikipedia.org/wiki/Hilbert_curve

r @jwolski

### CODE REVIEW

**Comment by jwolski** [comment]
:dancer:

**Comment by jwolski** [comment]
I'm sure the test is failing because of some silly reason. I'll look into it.... SOON

**Comment by benfleis** [comment]
the failure looks just like other tchannel `.listen` bugs we've fixed elsewhere. 10:1 odds anybody?

**Comment by kriskowal** [comment]
Rebased on the Master and now it is :green_apple: :green_apple:

**Comment by jwolski** [comment]
LEGGGITTTT

**Pull request merged**
